### ISSUE TITLE
No explicit deprecation annotation

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#102]
Properties and parameters in Google Cloud APIs may be marked as deprecated. Unfortunately, they are marked as such in description text, there's no dedicated field like `isDeprecated`. We have to do crazy checks like

```
strings.HasPrefix(lowerDesc, "deprecated") ||
strings.Contains(lowerDesc, ". deprecated") ||
strings.Contains(description, "(Deprecated") ||
strings.Contains(description, "Deprecated;") ||
strings.Contains(description, "Deprecated.") ||
strings.Contains(description, "[Deprecated]") ||
strings.Contains(description, "Deprecated in favor") ||
strings.Contains(description, "This field is deprecated")
```

which is ugly and can catch false positives. 

Is there a better way?

**Comment by mikhailshilkov** [comment]
@codyoss Could you point us to the place in the Go generator where it parses deprecation from textual descriptions?

**Comment by codyoss** [comment]
We do not currently do any special since there is not a great way to tell if a field is deprecated. We just inline the description of a field or resource into our docs.

Using a heuristic like you have above is the best that can be done today.

**Comment by mikhailshilkov** [comment]
https://bigquerydatatransfer.googleapis.com/$discovery/rest?version=v1 now has a `deprecated` annotation

**Comment by pinalbaldha** [comment]
Support for deprecation annotation has been added to the discovery documents
Refer: https://developers.google.com/discovery/v1/reference/apis, check `deprecated` and `enumDeprecated` properties.
