### ISSUE TITLE
Missing Secret Manager AddOn for container.Cluster

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-google-native#1059]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There is missing Secret Manager Add On config in container.Cluster resource. It is in GCP classic provider https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/#secret_manager_config_python

https://cloud.google.com/secret-manager/docs/secret-manager-managed-csi-component

**Comment by mjeffryes** [comment]
Hi @jancespivo, thanks for filing the issue. Unfortunately, we're not investing in enhancements for this provider at the moment. However, you can easily use multiple providers in your pulumi program, so you should be able to use these resources from the GCP provider. I would recommend defaulting to pulumi-gcp for any new programs.
