### ISSUE TITLE
BucketObject refreshing problem

### ISSUE THREAD

**Issue by hiteshboinpally** [pulumi/pulumi-google-native#106]
When deploying BucketObjects in folders, they consistently show up as needing to be "deleted" on subsequent `pulumi refresh` calls, despite the BucketObjects existing on the Console. A particular instance of this is talked about in this thread: https://pulumi.slack.com/archives/CBVJAP46L/p1622749292004000. 

Some workarounds:
- Deploy everything without the directory relationship. This isn't ideal since you lose the organization of the directory, amongst other issues but works.
- Deploy directories as zip files instead. This works, unless you need to access a particular file, for instance using `index.html` when deploying a website.

## Example

Below is an example of what this looks like after a `pulumi up` and then `pulumi refresh` immediately after -- no code changes were made between or edits in the gcp console.
<img width="1034" alt="Screen Shot 2021-06-03 at 1 17 48 PM" src="https://user-images.githubusercontent.com/67126616/120729576-61350280-c494-11eb-9ca0-0bd52c6687e9.png">

Expected: 
Object to show up as created and stay up as created.
Actual: 
Object shows up as created, but then is considered "deleted". This also struggles with deleting the stack, as the BucketObjects cannot be destroyed, instead getting this error: `
    error: error sending request: googleapi: got HTTP response code 404 with body: Not Found`.

**Comment by mikhailshilkov** [comment]
Probably related to https://github.com/pulumi/pulumi-google-native/issues/74

**Comment by mikhailshilkov** [comment]
@viveklak Do you want to take a look at this one next?

**Comment by mikhailshilkov** [comment]
I tried to reproduce this with a simple program

```
const bucket = new google.storage.v1.Bucket("bucket", {
    project,
    name: pulumi.interpolate`bucket-${randomString.result}`,
});

new google.storage.v1.BucketObject("app/backend/package.json", {
    name: "app/backend/package.json",
    bucket: bucket.name,
    source: new pulumi.asset.StringAsset("test"),
});
```

but it seems to be working fine for me...

**Comment by mikhailshilkov** [comment]
We refactored the implementation of the BucketObject since the issue was open, so I believe it's fixed. Let me know if anyone still has a repro.
