### ISSUE TITLE
Are enums strict?

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#121]
Discovery Documents define enums, each with a list of possible values. Does it mean that the list is complete and all other values will lead to a service error? Or is that list sometimes open where arbitrary values can be accepted?

**Comment by tequilarista** [comment]
We believe these to be strict values, but if you run into an example where that does not appear to be true, please log that.

**Comment by mikhailshilkov** [comment]
Thank you for confirming! I'll close this issue and log a new one if we ever find a counter-example.
