### ISSUE TITLE
Custom mutation support for container resources

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-google-native#124]
We should cover more update scenarios and make sure the replacement of clusters/nodepools is only triggered when necessary (i.e. the immutable properties of these resources are accurately tracked).

**Comment by mikhailshilkov** [comment]
This likely needs to be a manual implementation of Update methods (and corresponding Diff yielding no replacements). 

Cluster is relatively simple: we'd need to put updated properties inside an `update` map and prepend `desired` to property names.

Node pool is quite complicated as it has separate methods to update several groups of properties. See [this function](https://github.com/hashicorp/terraform-provider-google-beta/blob/889a6c013e7757b0f0592fe4ca275a781db9af5c/google-beta/resource_container_node_pool.go#L809) in the TF provider to get a sense of the complexity.

I suggest declaring some custom "updaters" that would apply to some resources, would declare which properties it can mutate, and then produce the payloads and actual calls with HTTP or Go SDK.

Separate attention should be given to awaiting of ready states, as the TF provider does quite a few of those.

Any better ideas @viveklak ?

**Comment by MitchellGerdisch** [comment]
Presumably this issue would also support loop-based creation of nodegroups.
Currently in GCP classic, I can have code like this:
```
for idx in range(2):
    np_name = f"basename-{idx}"
    node_pool = gcp.container.NodePool(np_name,
         cluster=gke_cluster.cluster.name,
         name=np_name,
         project=project,
         location=region,
     )
```
Because the classic provider nodepool creation logic sequences the nodepool creations.
But when trying this with google-native, one gets an 400 back from GCP about the second nodepool indicating that a nodepool creation is already in progress and to try again later.

**Comment by viveklak** [comment]
This issue will unblock https://github.com/pulumi/pulumi-google-native/issues/263 as well.
