### ISSUE TITLE
Error message displays property names in wrong casing

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#141]
Example: try provisioning a GKE cluster (`container/v1:Cluster`) without specifying a value for `initialNodeCount`. The service returns the following error:

> Error 400: Cluster.initial_node_count must be greater than zero.: "https://container.googleapis.com/v1/projects/pulumi-development/locations/us-central1/clusters"

Note that the message says `initial_node_count` which is incorrect capitalization of the `initialNodeCount` as (correctly) defined by discovery documents.

**Comment by codyoss** [comment]
> Note that the message says initial_node_count which is incorrect capitalization...

I assume most error messages will be like this since that is the field name as defined in the [proto](https://github.com/googleapis/googleapis/blob/e610c3bbc75e66fcfd5d7c46fab225c5978700df/google/container/v1/cluster_service.proto#L1160).

**Comment by mnlumi** [comment]
`initial_node_count` has been deprecated and is no longer required. Closing issue.
