### ISSUE TITLE
Create a listXyz() function along with the getXyz() for each resource

### ISSUE THREAD

**Issue by ravikumarrao** [pulumi/pulumi-google-native#144]
I would like to [list all the subnetworks](https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/list) in a given project using pulumi google native provider, looks like today we only have the `getXyz()` function generated from the [schema.go](https://github.com/pulumi/pulumi-google-native/blob/087a4ee255de7aca15a7ef3e83ca567b85c1fbcb/provider/pkg/gen/schema.go#L151) which gives me [getSubnetwork](https://www.pulumi.com/docs/reference/pkg/gcp/compute/subnetwork/#look-up), but there is no equivalent to the [subnetworks list](https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/list) method.

`GET https://compute.googleapis.com/compute/v1/projects/{project}/regions/{region}/subnetworks` 

Please add support for listing resources.

ref slack post: https://pulumi-community.slack.com/archives/CRFUR2DGB/p1625604334049200

**Comment by mikhailshilkov** [comment]
Hi @ravikumarrao thank you for opening this issue.

I think this is our standard approach across multiple providers. We are focused on managing resources with CRUD operations and don't provide extra functions to list or search.

As a workaround, you could use Google Cloud SDKs from you Pulumi program to call those operations.

**Comment by ravikumarrao** [comment]
Made it work with Google SDK.
