### ISSUE TITLE
ServiceNetworking API Missing

### ISSUE THREAD

**Issue by akath19** [pulumi/pulumi-google-native#150]
The ServiceNetworking API, required for creating VPC peerings and allowing several services to work with private IP addresses is missing on all SDKs, the discovery document can be found in `discovery/servicenetworking_v1.json` and `discovery/servicenetworking_v1beta1.json`, however, no SDK methods exist and there's no code in the repo for it

## Steps to reproduce

1. Use any Google Native SDK
2. Look for servicenetworking API

Expected: ServiceNetworking API is not available
Actual: ServiceNetworking API should be available for use

**Comment by mikhailshilkov** [comment]
Hi @akath19 thank you for reporting this!

Which specific resources would you need from that module? `Connection`? The `Connection` resource is likely blocked by https://github.com/pulumi/pulumi-google-native/issues/47.

**Comment by akath19** [comment]
Yeah, `Connection` is the one I need, my stack creates a new `Network` & CloudSQL `Instance` but the `instance` fails because the `Network`  needs to be paired with a `Connection` to use private IPs.

All other resources APIs I've used work flawlessly!

**Comment by mikhailshilkov** [comment]
Thank you for coming back to us on this. I'll try to prioritize adding this resource. As a workaround, you should be able to mix the classic GCP provider into your code and use this particular resource from there.

**Comment by akath19** [comment]
Awesome, it works flawlessly mixing classic & native!
