### ISSUE TITLE
Pulumi crashes when cloud armor rule is updated with new IP ranges

### ISSUE THREAD

**Issue by sghosh-discovery** [pulumi/pulumi-google-native#160]
We wanted to update the IP whitelisting range for the cloud armor. Pulumi crashes with it.

For example, see the code:

```
const edgeSecurityPolicy = new SecurityPolicy(name('sec-policy-edge', getSuffix()), {
        project: environment.project.gcp.projectId,
        description: 'Edge Security Policy',
        type: SecurityPolicyType.CloudArmorEdge,
        rules: [
            {
                action: 'allow',
                priority: 1000,
                match: {
                    versionedExpr: 'SRC_IPS_V1',
                    config: {
                        srcIpRanges: ipRanges,
                    },
                },
            },
            {
                action: 'deny(403)',
                priority: 2147483647,
                match: {
                    versionedExpr: 'SRC_IPS_V1',
                    config: {
                        srcIpRanges: ['*'],
                    },
                },
            },
        ],
    });
```

If you add more IP ranges in the array ipRanges, pulumi crashes.

## Steps to reproduce

1. Create a Google Cloud Armor security policy with source IP range
2.  Update the source IP range to add more IPs
3.
4.

Expected: 
No crash
Actual: 

```
            type       : "CLOUD_ARMOR_EDGE"
    panic: runtime error: index out of range [7] with length 7
    
    goroutine 42 [running]:
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0000a6008, 0xc001476878, 0xcc2660, 0xc001518a80, 0xcc2660, 0xc001518c60, 0xc001476820, 0x0, 0xc0014767f8)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:68 +0x9d4
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0000a6008, 0xc000480e40, 0xc001524960, 0xc001524c90, 0xc000f2adc0)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0000a6008, 0xc001476be0, 0xd1db80, 0xc001524960, 0xd1db80, 0xc001524c90, 0xc001476b88, 0xc001476bb0, 0x40d99b)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0000a6008, 0xc000480e10, 0xc001524930, 0xc001524c60, 0xc000f17760)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0000a6008, 0xc001476f48, 0xd1db80, 0xc001524930, 0xd1db80, 0xc001524c60, 0xc001476ef0, 0xcc9620, 0xc001478f58)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0000a6008, 0xc000480d20, 0xc0015248d0, 0xc001524c30, 0xc000f04fa0)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0000a6008, 0xc000dba0a0, 0xd1db80, 0xc0015248d0, 0xd1db80, 0xc001524c30, 0xc0014773e0, 0x7fa93be7dbc0, 0x8)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0000a6008, 0xc001477438, 0xcc2660, 0xc001518af8, 0xcc2660, 0xc001518cd8, 0xc0014773e0, 0xcd56e0, 0xc00152a860)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:68 +0x2d7
    
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0000a6008, 0xc000909410, 0xc0015248a0, 0xc001524a50, 0x3)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).prepareAPIInputs(0xc0000a2360, 0xc00150b950, 0xc00150bd40, 0xc000909410, 0x1)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:379 +0x7a
    
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).Update(0xc0000a2360, 0xf71b28, 0xc00150b920, 0xc0000d5c80, 0xc0000a2360, 0xd24001, 0xc00151bc00)
    
    	/home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:537 +0x573
    
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1(0xf71b28, 0xc00150b920, 0xe0ea20, 0xc0000d5c80, 0xe021e0, 0x16d03a0, 0xf71b28, 0xc00150b920)
    
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/proto/go/provider.pb.go:2305 +0x8b
    
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xf71b28, 0xc00150ae40, 0xe0ea20, 0xc0000d5c80, 0xc00009d460, 0xc001518018, 0x0, 0x0, 0xf5e9a0, 0xc0002cd6a0)
    
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler(0xe227e0, 0xc0000a2360, 0xf71b28, 0xc00150ae40, 0xc0000a33e0, 0xc000031c60, 0xf71b28, 0xc00150ae40, 0xc0003a5c00, 0xad3)
    
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/proto/go/provider.pb.go:2307 +0x150
    
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004fc380, 0xf7a638, 0xc0001ae780, 0xc001509d40, 0xc0012dfbc0, 0x1692df8, 0x0, 0x0, 0x0)
    
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    
    google.golang.org/grpc.(*Server).handleStream(0xc0004fc380, 0xf7a638, 0xc0001ae780, 0xc001509d40, 0x0)
    
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0013d7960, 0xc0004fc380, 0xf7a638, 0xc0001ae780, 0xc001509d40)
    
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
```

**Comment by mikhailshilkov** [comment]
This crash will be fixed in the upcoming 0.6.0. However, the update still fails with a different cause, so I failed a new issue to track it: https://github.com/pulumi/pulumi-google-native/issues/164

Sorry for the inconvenience.

**Comment by sghosh-discovery** [comment]
This problem is back @mikhailshilkov 

panic: runtime error: index out of range [1] with length 1
    goroutine 41 [running]:
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166e878, 0x18c11c0, 0xc001691410, 0x18c11c0, 0xc001691890, 0xc00166e820, 0x18c11c0, 0xc001691908)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:68 +0x9d4
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc00059bad0, 0xc0016a63c0, 0xc0016a6b70, 0xc0010967f0)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166ebe0, 0x191cf00, 0xc0016a63c0, 0x191cf00, 0xc0016a6b70, 0xc00166eb88, 0x191cf00, 0xc0016a6de0)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc00059baa0, 0xc0016a6390, 0xc0016a6b40, 0xc001095470)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166ef48, 0x191cf00, 0xc0016a6390, 0x191cf00, 0xc0016a6b40, 0xc00166eef0, 0x18d4360, 0xc00169fe90)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc00059b9b0, 0xc0016a6330, 0xc0016a6b10, 0xc00108f3c0)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc001037090, 0x191cf00, 0xc0016a6330, 0x191cf00, 0xc0016a6b10, 0xc00166f3e0, 0x191cf00, 0xc0016a6d80)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166f438, 0x18c11c0, 0xc001691488, 0x18c11c0, 0xc0016918a8, 0xc00166f3e0, 0x18d4360, 0xc00169fb30)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:68 +0x2d7
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc000b3d380, 0xc0016a6000, 0xc0016a64b0, 0x1)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).prepareAPIInputs(0xc00009e0c0, 0xc0016819e0, 0xc00168c570, 0xc000b3d380, 0x1)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:379 +0x7a
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).Update(0xc00009e0c0, 0x1b718a8, 0xc0016819b0, 0xc000239380, 0xc00009e0c0, 0x1923301, 0xc001685a80)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:537 +0x573
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1(0x1b718a8, 0xc0016819b0, 0x1a0dfa0, 0xc000239380, 0x1a01620, 0x22d40f8, 0x1b718a8, 0xc0016819b0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/proto/go/provider.pb.go:2305 +0x8b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1b718a8, 0xc001680390, 0x1a0dfa0, 0xc000239380, 0xc0015fc400, 0xc0015e39b0, 0x0, 0x0, 0x1b5e5a0, 0xc00028f760)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler(0x1a22000, 0xc00009e0c0, 0x1b718a8, 0xc001680390, 0xc00009f7a0, 0xc0001b5c20, 0x1b718a8, 0xc001680390, 0xc000339500, 0x14f6)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/proto/go/provider.pb.go:2307 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000540380, 0x1b7a538, 0xc0005a2d80, 0xc0015f9200, 0xc0014b3bf0, 0x2296f98, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc000540380, 0x1b7a538, 0xc0005a2d80, 0xc0015f9200, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005e8020, 0xc000540380, 0x1b7a538, 0xc0005a2d80, 0xc0015f9200)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

**Comment by mikhailshilkov** [comment]
The stack trace suggests you are still using the old provider version, as a panic isn't possible on line `convert.go:68` with the current code. Could it be that the resource is still managed by the old provider version? Any chance you could try it on a clean stack/resource?
