### ISSUE TITLE
Add `getEngineVersions` function for GKE resources

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-google-native#166]
Our pulumi-gcp provider includes a [`getEngineVersions`](https://github.com/pulumi/pulumi-gcp/blob/master/sdk/nodejs/container/getEngineVersions.ts) function to programmatically get the version number for GKE clusters. The native provider should also add this functionality.

Here is the relevant implementation: https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/data_source_google_container_engine_versions.go

## Affected feature

GKE clusters

**Comment by viveklak** [comment]
We should be able to accomplish the equivalent of this by exposing an invoke for `getServerConfig` https://github.com/pulumi/pulumi-google-native/blob/master/discovery/container_v1.json#L161
