### ISSUE TITLE
Updates to fields not in updateProperties are silently ignored

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-google-native#170]
e.g. create a GKE cluster and update a field. Since the update properties at the time of filing only includes `name`, update any field and run an update. The state is updated to reflect the new setting but no corresponding update is actually performed.

**Comment by mikhailshilkov** [comment]
@viveklak Do you have a repro for this handy? I'm starting with this example: https://github.com/pulumi/pulumi-google-native/tree/master/examples/gke-ts and then trying to change a field and update.

1. Changed `initialClusterVersion` => preview shows a replace operation
2. Added `enableTpu: true,` => preview shows an update (likely wrong!) but the actual update fails with `Error 400: Must provide an update`
3. Added `description: "bla"` => same as (2)

I'm using 0.6.0.

**Comment by viveklak** [comment]
I think it was 2/3 that I was hitting with a local provider which might have leaked a no-op update through? I think we can link this with #181 for now.
