### ISSUE TITLE
Code update for Cloud function does not get deployed

### ISSUE THREAD

**Issue by Rugal** [pulumi/pulumi-google-native#177]
Trying to play around with google native pulumi, using the example directly and changing the response to verify the updates to deployment.

After check the cloud storage and download the `zip` file, I also found that the content never updates.

## Steps to reproduce

1. clone pulumi example
2. go to folder `google-native-ts-functions`
3. `pulumi up`
4. change python code to return something different
5. `pulumi up` again

Expected: to get new response from second deployment
Actual: get the same response as the very first deployment, even after waiting for some time

**Comment by lukehoban** [comment]
We most likely need to support Assets/Archives in these places that accept filenames, to ensure that we can automatically do the change detection on the contents.

**Comment by mikhailshilkov** [comment]
@lukehoban We do this here already: https://github.com/pulumi/examples/blob/master/google-native-ts-functions/index.ts#L30 (and https://github.com/pulumi/pulumi-google-native/blob/master/examples/functions-ts/index.ts#L11)

**Comment by lukehoban** [comment]
Ahh - I see. I believe the issue is that the bucketobject will be updated, but there is nothing to indicate to the function that it needs to update (to use the newly uploaded code) - as none of its inputs have changed. 

For examples like this - we’ll likely need to add something to make sure the function gets updated in these cases. One option would be to add `replaceOnChanges` to the bucket object, so that a new object is created on each code change. 

It’s possible functions have some other input available to trigger this though?

**Comment by Rugal** [comment]
I thought any change would trigger the update, so I have to explicitly do some infra change in order to see the difference?

Also, after the update, I went to cloud storage and downloaded the zip file. I can confirm that the unzipped file is still the old version response.

**Comment by lukehoban** [comment]
> Also, after the update, I went to cloud storage and downloaded the zip file. I can confirm that the unzipped file is still the old version response.

That is surprising. That indicates the issue is not what I suggested above.  @mikhailshilkov will likely need to look more deeply into this.

**Comment by mikhailshilkov** [comment]
Hi @Rugal

Here is my repro with 0.6.0 vesion of the provider. I deploy the following program:

```
import * as pulumi from "@pulumi/pulumi";
import * as google from "@pulumi/google-native";

const bucket = new google.storage.v1.Bucket("bucket");

const bucketObject = new google.storage.v1.BucketObject("bucketObject", {
    bucket: bucket.name,
    source: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive("./pythonfunc"),
    }),
});

const func = new google.cloudfunctions.v1.Function("function-py", {
    sourceArchiveUrl: pulumi.interpolate`gs://${bucket.name}/${bucketObject.name}`,
    httpsTrigger: {
        securityLevel: google.cloudfunctions.v1.HttpsTriggerSecurityLevel.SecureAlways,
    },
    entryPoint: "handler",
    timeout: "60s",
    availableMemoryMb: 128,
    runtime: "python37",
    ingressSettings: "ALLOW_ALL",
});

const invoker = new google.cloudfunctions.v1.FunctionIamPolicy("function-py-iam", {
    functionId: func.name.apply(name => name.split("/")[name.split("/").length-1]),
    bindings: [
        {
            members: ["allUsers"],
            role: "roles/cloudfunctions.invoker",
        }
    ],
});

export const functionUrl = func.httpsTrigger.url;
```

then I change the function body (in `main.py`) and run `pulumi up` again. I get the following preview:

```
     Type                                         Name                  Plan        Info
     pulumi:pulumi:Stack                          google-native-ts-dev              
 +-  ├─ google-native:storage/v1:BucketObject     bucketObject          replace     [diff: ~name,source]
 ~   └─ google-native:cloudfunctions/v1:Function  function-py           update      [diff: ~sourceArchiveUrl]
```

which, when confirmed, deletes the old blob, creates a new blob with a new name (it's autonamed in my program), and updates the function with a new URL. After this change, the Function code is applied.

Could you give the above code a try? Note that all resources are auto-named which I think helps in the case of the bucket object replacement.

Also note that I found a regression in 0.7.0: #185.

**Comment by Rugal** [comment]
Hi @mikhailshilkov ,

Thanks for testing it out. 
Did you try to hit the endpoint before and after and see the difference?
I did the test multiple times and the `pulumi up` does show the change, but when I hit the endpoint, it never change.

**Comment by mikhailshilkov** [comment]
Yes, I did, and it worked for me in the described configuration.

**Comment by Rugal** [comment]
Hi @mikhailshilkov ,

I just did the test, 

1. cloning the `example` repository 
2. navigate into google-native-ts-functions
3. change the response as `Before Rugal`
4. `pulumi up`
5. then I use `httpie` to test the endpoint 
    `http $(pulumi stack output functionUrl)  "Authorization: Bearer $(gcloud auth print-identity-token)"`

    ![image](https://user-images.githubusercontent.com/1812023/128726163-a13b8379-bee6-4bda-b8c3-9ea34a9b238d.png)

1. Then I made change to python response to `After Rugal`
    ![image](https://user-images.githubusercontent.com/1812023/128727575-48c63f7b-b88c-4057-9f4c-8b63463c36fc.png)

1. Then I did the updates, I hit `yes`

    ![image](https://user-images.githubusercontent.com/1812023/128726241-3c292176-aaa0-4a7a-8024-5de0821df6f0.png)


1. Then I use the last `httpie` command to test endpoint again
    ![image](https://user-images.githubusercontent.com/1812023/128726872-08504848-03ff-4d7b-afef-fa6e955ef531.png)
    This still gives me the same response, even after waiting like 5 mins

**Comment by mikhailshilkov** [comment]
Are you on google-native 0.5.0 or later? There was a fix for `BucketObject` in that version.

Are you still seeing that the actual binary is not updated or is it the case that the Function doesn't pull the updated-in-place binary?

By the way, I've just merged a PR to that example to enable auto-naming and other clean-up changes.

**Comment by Rugal** [comment]
It is fixed after upgrading the library, thanks for the clarification.
