### ISSUE TITLE
Format for IDs is different between Google Native and GCP providers

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-google-native#179]
In the new Google Native provider, the resource IDs have the format: `folders/702283483512` whereas the GCP provider, it's the same without the `folders` prefix.

If we're going to have interoperability between the providers, they're going to need to be the same as it would be a shame for every single user to have to write code to strip out the `folders/` part

**Comment by mikhailshilkov** [comment]
Let's track more broadly in #190
