### ISSUE TITLE
Add BigQuery resource for query

### ISSUE THREAD

**Issue by ColeSiegelTR** [pulumi/pulumi-google-native#191]
## Affected feature

As part of my deployment i need to run something in BigQuery and then verify that it was successful. Currently the Pulumi API supports executing the query through the creation of a **job** but confirming the execution status requires custom code. I am not entirely sure how to implement waiting periods/periodic polling for status updates inside the Pulumi logic myself. I've found that Google already has an endpoint to run a query synchronously and return the result after timeout period, which is exactly what I need to do. Are there any plans to expose this resource?

https://www.pulumi.com/docs/reference/pkg/google-native/bigquery/v2/
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query

## Summary
Addition of BigQuery query resource, so that I can specify a query and timeout period as exposed in BigQuery v2 api. Pulumi should only complete the deployment if the query returns successfully within the timeout period.

**Comment by mikhailshilkov** [comment]
Thank you for your question. Correct me if I'm wrong but this API doesn't seem to fit very well into the model of resources. Okay, you can "create" a query and get the results in outputs. But what should happen on update? On refresh? On delete?

**Comment by ColeSiegelTR** [comment]
Hi @mikhailshilkov 

Wouldn't the same questions also exist for BigQuery jobs, which there is a resource for, since they get executed on creation anyway? I'm just looking for the **query** resource to be exposed like **job** is so that I can run the query synchronously instead of completing the deployment when the job is actually in error state.

https://www.pulumi.com/docs/reference/pkg/google-native/bigquery/v2/job/

**Comment by mikhailshilkov** [comment]
Jobs have APIs to insert, delete, and get, which makes it look like a proper resource. Query is  a single API method.

You could potentially use Google's own SDKs to query the job from your Pulumi program. Would that be an option?

**Comment by ColeSiegelTR** [comment]
Thank you very much for the suggestion @mikhailshilkov I was able to do that to retrieve the job status:

```
export const jobResult = initJob.jobId.apply(jobId => {
    const bigQuery = new BigQuery();
    const results = bigQuery.job(jobId).getQueryResults({
        location: config.region,
        timeoutMs: config.bigquery.timeoutMs,
    });
});
```
