### ISSUE TITLE
monitoring.v3.AlertPolicy creation fails due to auto-populated 'name' field

### ISSUE THREAD

**Issue by roekatz** [pulumi/pulumi-google-native#193]
When creating an alert policy through google's API, the name field shouldn't be set.
Seems like `AlertPolicy` auto-generates a name, which fails the API call.

## Code 

```
import pulumi_google_native as gnative

alert_policy = gnative.monitoring.v3.AlertPolicy("alert-policy",
    combiner="OR",
    conditions=[gnative.monitoring.v3.ConditionArgs(
        condition_matched_log=gnative.monitoring.v3.LogMatchArgs(
            filter="textPayload=~\"ERROR\"",
        ),
        display_name="Error log",
    )],
    alert_strategy=gnative.monitoring.v3.AlertStrategyArgs(
        notification_rate_limit=gnative.monitoring.v3.NotificationRateLimitArgs(
            period="900s"
        )
    ),
    display_name="Error Alert")
```

## Output

>   google-native:monitoring/v3:AlertPolicy (alert-policy):
>     error: error sending request: googleapi: Error 400: Cannot set 'name' when creating alert policy. Tried to set to 'projects/proj-1234/alertPolicies/alert-policy-d23d53c'.: "https://monitoring.googleapis.com/v3/projects/proj-1234/alertPolicies" map[combiner:OR conditions:[map[conditionMatchedLog:map[filter:textPayload=~"ERROR"] displayName:Error log]] displayName:Error Alert name:projects/proj-1234/alertPolicies/alert-policy-d23d53c project:proj-1234]

**Comment by mikhailshilkov** [comment]
Indeed, it looks like we should only populate it on update:

> Required if the policy exists. The resource name for this policy. The format is: projects/[PROJECT_ID_OR_NUMBER]/alertPolicies/[ALERT_POLICY_ID] [ALERT_POLICY_ID] is assigned by Stackdriver Monitoring when the policy is created. When calling the alertPolicies.create method, do not include the name field in the alerting policy passed as part of the request.

**Comment by mszewczyk-ipwt** [comment]
+1

**Comment by viveklak** [comment]
Tracked in #291
