### ISSUE TITLE
firebaserules resources fail to properly set the rules

### ISSUE THREAD

**Issue by JacksonMaxfield** [pulumi/pulumi-google-native#196]
`pulumi_google_native.firebaserules.v1.Ruleset` and `from pulumi_google_native.firebaserules.v1.Release` fail to properly apply to a newly generated Firebase Project.

My attempted implementation of these resources can be found here: https://github.com/CouncilDataProject/cdp-backend/blob/admin/prepare-public-read/cdp_backend/infrastructure/cdp_stack.py#L171

## Steps to reproduce

The best method for a reproduction can be found on a branch of the project repository: https://github.com/CouncilDataProject/cdp-backend/tree/admin/prepare-public-read

Using that branch, the steps to reproduce are:

1. `git clone https://github.com/CouncilDataProject/cdp-backend.git`
2. `cd cdp-backend`
3. `git checkout admin/prepare-public-reader`
4. `pip install -e .[dev]`
5. `cd dev-infrastructure/`
6. `make login`
7. `make init project={SOME-UNIQUE-PROJECT-ID}`
8. `make gen-key project={SOME-UNIQUE-PROJECT-ID}`
9. `export GOOGLE_CREDENTIALS=$(cat ../.keys/cdp-dev.json)`
10. `make build`

If you don't want to clone the repository and use the provided make commands, in short the steps above do the following:
1. Login into Pulumi and GCloud CLI util
2. Create a new Google Project
3. Initialize a Pulumi Stack
4. Generate a Service Account JSON key for use as the `GOOGLE_CREDENTIALS` environment variable
5. Build the infrastructure as defined in: https://github.com/CouncilDataProject/cdp-backend/blob/admin/prepare-public-read/cdp_backend/infrastructure/cdp_stack.py (`make build` runs `pulumi up -p 4`)

Afterwards you can destroy all of these resources with `make destroy project={SOME-UNIQUE-PROJECT-ID}`

---

Then to see if the rulesets were applied, navigate to https://console.firebase.google.com, select your project (it will be the same as the `{SOME-UNIQUE-PROJECT-ID}` from above), on the left side tab select either `Firestore Database` or `Storage` then on the center navigation tabs, select `Rules`.

This entire process can be seen in the following video (it is edited to cut out the parts where I am just waiting for resource / accounts to setup): 

https://user-images.githubusercontent.com/17132317/132254347-0186f046-220c-4f4c-a08f-109f7a686e58.mp4

---

Expected:  The provided Rulesets to be applied
Actual:  No ruleset(s) are applied

**Comment by mikhailshilkov** [comment]
Hi @JacksonMaxfield thank you for the time spent on this great repro!

I couldn't see it on the video - do I understand correctly that all operations succeed without errors but you don't see the effect taking place? Would it be possible to share your Pulumi state (`pulumi stack export`). You can share it privately at mikhail@pulumi.com if you want to, or be sure to obfuscate any sensitive information if sharing on GitHub.

**Comment by JacksonMaxfield** [comment]
Hey @mikhailshilkov!

Yes build completes with no errors but the actual security rules aren't being applied. This could just be a documentation thing but it could also be on the Firebase side imo. Firebase is pretty particular about how you do things I have found, from my perspective this could legitimately be one of or a combination of:

1. Pulumi Google Native bug
2. Firebase bug
3. Order of operations (fixed with documentation)

Will generate a stack and send it to you in email :+1:

**Comment by JacksonMaxfield** [comment]
Hey @mikhailshilkov there doesn't seem to be a resolution on Firebase side. The Firebase support team doesn't believe it is an issue on their side even though I have shown the bug with Pulumi and with Terraform + their JS API. I am going to close this for now but if anyone else finds this issue please keep me posted.
