### ISSUE TITLE
compute.*.NetworkEndpointGroup and BackendService missing region

### ISSUE THREAD

**Issue by mszewczyk-ipwt** [pulumi/pulumi-google-native#198]
classes:
* `compute.*.NetworkEndpointGroup`
* `compute.*.BackendService`

are missing `region` parameter. It is required when using serverless connector and it is also described in the specification: 
https://cloud.google.com/compute/docs/reference/rest/v1/networkEndpointGroups/insert

also `zone` is set to be required by the Resource which is not true in the API - should be optional.

**Comment by mikhailshilkov** [comment]
According to the doc that you linked, `zone` is a part of the HTTP URL:

> POST https://compute.googleapis.com/compute/v1/projects/{project}/zones/{zone}/networkEndpointGroups

That's why it's required.

`region` is described as "output only":

> [Output Only] The URL of the region where the network endpoint group is located.

Am I reading it wrong?

**Comment by mszewczyk-ipwt** [comment]
My misunderstanding of Google API, closing.
