### ISSUE TITLE
Pulumi crashes when cloud armor rule is updated with new IP ranges #160

### ISSUE THREAD

**Issue by sghosh-discovery** [pulumi/pulumi-google-native#228]
This issue is repeating itself.
Originally present in https://github.com/pulumi/pulumi-google-native/issues/160

panic: runtime error: index out of range [1] with length 1
    goroutine 41 [running]:
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166e878, 0x18c11c0, 0xc001691410, 0x18c11c0, 0xc001691890, 0xc00166e820, 0x18c11c0, 0xc001691908)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:68 +0x9d4
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc00059bad0, 0xc0016a63c0, 0xc0016a6b70, 0xc0010967f0)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166ebe0, 0x191cf00, 0xc0016a63c0, 0x191cf00, 0xc0016a6b70, 0xc00166eb88, 0x191cf00, 0xc0016a6de0)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc00059baa0, 0xc0016a6390, 0xc0016a6b40, 0xc001095470)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166ef48, 0x191cf00, 0xc0016a6390, 0x191cf00, 0xc0016a6b40, 0xc00166eef0, 0x18d4360, 0xc00169fe90)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc00059b9b0, 0xc0016a6330, 0xc0016a6b10, 0xc00108f3c0)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc001037090, 0x191cf00, 0xc0016a6330, 0x191cf00, 0xc0016a6b10, 0xc00166f3e0, 0x191cf00, 0xc0016a6d80)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:42 +0x82d
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).convertPropValue(0xc0001ac038, 0xc00166f438, 0x18c11c0, 0xc001691488, 0x18c11c0, 0xc0016918a8, 0xc00166f3e0, 0x18d4360, 0xc00169fb30)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:68 +0x2d7
    github.com/pulumi/pulumi-google-native/provider/pkg/resources.(*SdkShapeConverter).SdkPropertiesToRequestBody(0xc0001ac038, 0xc000b3d380, 0xc0016a6000, 0xc0016a64b0, 0x1)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/resources/convert.go:102 +0x2da
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).prepareAPIInputs(0xc00009e0c0, 0xc0016819e0, 0xc00168c570, 0xc000b3d380, 0x1)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:379 +0x7a
    github.com/pulumi/pulumi-google-native/provider/pkg/provider.(*googleCloudProvider).Update(0xc00009e0c0, 0x1b718a8, 0xc0016819b0, 0xc000239380, 0xc00009e0c0, 0x1923301, 0xc001685a80)
        /home/runner/work/pulumi-google-native/pulumi-google-native/provider/pkg/provider/provider.go:537 +0x573
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1(0x1b718a8, 0xc0016819b0, 0x1a0dfa0, 0xc000239380, 0x1a01620, 0x22d40f8, 0x1b718a8, 0xc0016819b0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/proto/go/provider.pb.go:2305 +0x8b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1b718a8, 0xc001680390, 0x1a0dfa0, 0xc000239380, 0xc0015fc400, 0xc0015e39b0, 0x0, 0x0, 0x1b5e5a0, 0xc00028f760)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler(0x1a22000, 0xc00009e0c0, 0x1b718a8, 0xc001680390, 0xc00009f7a0, 0xc0001b5c20, 0x1b718a8, 0xc001680390, 0xc000339500, 0x14f6)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/proto/go/provider.pb.go:2307 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000540380, 0x1b7a538, 0xc0005a2d80, 0xc0015f9200, 0xc0014b3bf0, 0x2296f98, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc000540380, 0x1b7a538, 0xc0005a2d80, 0xc0015f9200, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005e8020, 0xc000540380, 0x1b7a538, 0xc0005a2d80, 0xc0015f9200)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

**Comment by sghosh-discovery** [comment]
pulumi version
v3.16.0

Google native: 0.8.0

**Comment by mikhailshilkov** [comment]
Let's keep the discussion in #160
