### ISSUE TITLE
Operation replaced (delete/create),  instead of update

### ISSUE THREAD

**Issue by aleon80** [pulumi/pulumi-google-native#243]
Hi,

I'm trying to update a version at GKE cluster via pulumi/google-native but I get recreate cluster and loss access to gke and I need redeploy all manifests

`  +-google-native:container/v1beta1:NodePool: (replace)
      ~ version          : "1.22.2-gke.1901" => "1.22.3-gke.700"`

`     Type                                         Name                               Plan        Info
     pulumi:pulumi:Stack                          cloud-gke
 +-  ├─ google-native:container/v1beta1:NodePool  nodepool-one  replace     [diff: ~version]
 +-  └─ google-native:container/v1beta1:Cluster  kcge-cluster        replace     [diff: ~initialClusterVersion,nodePools]`
 
 What is the logic behind whether an update should result in delete/re-create or in-place update?

**Comment by mikhailshilkov** [comment]
This is another instance of  https://github.com/pulumi/pulumi-google-native/issues/185 - we planned to fix it this week.

**Comment by aleon80** [comment]
> This is another instance of #185 - we planned to fix it this week.


Thank you.
