### ISSUE TITLE
Exclude certain resources from autonaming

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-google-native#291]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
This is a general tracker for resources which the provider should not attempt to inject names automatically for (since the backing service is expected to name them):

Closed duplicates:
- [ ] https://github.com/pulumi/pulumi-google-native/issues/222
- [ ] https://github.com/pulumi/pulumi-google-native/issues/206
- [ ] https://github.com/pulumi/pulumi-google-native/issues/193
- [ ] https://github.com/pulumi/pulumi-google-native/issues/317

**Comment by roekatz** [comment]
@viveklak I might be interested in implementing it
