### ISSUE TITLE
Identify gaps between resources that are easily automated and resources that customers need -- build a plan for resources that need to be implemented manually.

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-google-native#3]

**Comment by viveklak** [comment]
As noted in https://github.com/pulumi/pulumi-google-native/issues/18, the essential use cases seemed to be covered with the current native provider. That said, we may still have missing pieces.
As far as fallbacks for implementing custom resources is concerned, we have a few options:
1. We could explore integrating with DCL if that covers such resources (https://github.com/pulumi/pulumi-google-native/issues/5)
2. Implement on top of SDK client as we did in azure-native.
