### ISSUE TITLE
Pause/resume Cloud Scheduler jobs

### ISSUE THREAD

**Issue by Ezard** [pulumi/pulumi-google-native#331]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi does not allow Cloud Scheduler jobs to be paused/resumed. Pause/resume methods are available in `v1beta1` of the Cloud Scheduler API: https://cloud.google.com/scheduler/docs/reference/rest, https://cloudscheduler.googleapis.com/$discovery/rest?version=v1beta1.

I assume that this might need to be a handcrafted feature within Pulumi, to allow something like `isPaused: boolean` to be specified for Job resources, or allow the `state` field (which is currently only available as an output) to be set to a subset of the available states

**Comment by guineveresaenger** [comment]
This feature sounds like it would be changing cloud resources in flight, which may not fit well with Pulumi's declarative resource model. You may be better off using the Google SDK in your preferred language for this operation.
