### ISSUE TITLE
Unable to enable GKE Workload Monitoring

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-google-native#407]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd like to enable `WORKLOAD` monitoring for GKE clusters, but it appears only `SYSTEM_COMPONENTS` is allowed in `typescript.

The classic provider does allow for `WORKLOADS` and so does [`gcloud`](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#--monitoring)

### Affected area/feature

GKE

**Comment by KaoruDev** [comment]
as a workaround:

```typescript
"WORKLOAD" as MonitoringComponentConfigEnableComponentsItem,
```

**Comment by guineveresaenger** [comment]
Hi @KaoruDev!

Thank you for filing this issue. This provider is still in preview, and we are working to bring it up to feature parity with the classic provider. 

Please let us know if you'd like to help with adding this feature, and we'll be more than happy to show you around.

**Comment by viveklak** [comment]
@KaoruDev - thanks for filing the issue. FWIW I think the v1beta resource does support the WORKLOADS MonitoringComponentConfig: https://www.pulumi.com/registry/packages/google-native/api-docs/container/v1beta1/cluster/#loggingcomponentconfigenablecomponentsitem. You might have been looking at the v1 cluster? Google Native builds on top of the versioned API specifications from Google. The classic provider leverages the beta cluster resource by default. Google native offers each of the API versions as distinct resources. Hope this helps!

**Comment by KaoruDev** [comment]
Ah, hrmm, does that mean when the `v1` endpoint is no longer in beta, I will have to import the cluster?

**Comment by viveklak** [comment]
> Ah, hrmm, does that mean when the `v1` endpoint is no longer in beta, I will have to import the cluster?

Its determined by the API specifications that Google applies. In general the changes to v1beta etc. have been additive and will persist with some changes potentially being promoted from beta to v1 eventually. However, given the `beta` name, they may potentially introduce breaking changes. From my understanding the v1beta endpoint has been supported for a long time.

**Comment by KaoruDev** [comment]
sorry, I mean that if I were to create a GKE cluster using the `v1beta` Cluster class, when that v1beta endpoint gets deprecated, would I have to switch to the v1 class because Pulumi's `urn` is now different? Which means I'd have to import that GKE cluster when switching over, or am I missing something?

**Comment by viveklak** [comment]
> 

I guess my point is that I don't see the v1beta endpoint getting deprecated (but I don't work at Google so can't guarantee this). As it stands, the gcp classic provider is always using the v1beta endpoint behind the scenes (wraps google-beta provider).

**Comment by KaoruDev** [comment]
Gotcha thanks for the info and forgive me for my misunderstanding.
