### ISSUE TITLE
Does not support enabling Managed Service for Prometheus 

### ISSUE THREAD

**Issue by praveenperera** [pulumi/pulumi-google-native#409]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Google has an option to enable Managed Service for Prometheus on cluster >= 1.21. I am unable to find this option in the `google-native` package

**Comment by viveklak** [comment]
This is only available in the v1beta version of the api: see https://www.pulumi.com/registry/packages/google-native/api-docs/container/v1beta1/cluster/#managedprometheusconfig

**Comment by naveensrinivasan** [comment]
@viveklak  Is it available in the `go` pkg? I couldn't find it. Could you please point me to it?

**Comment by viveklak** [comment]
> @viveklak Is it available in the `go` pkg? I couldn't find it. Could you please point me to it?
https://github.com/pulumi/pulumi-google-native/blob/b588371cbcffbffb9dce59e5848353c7f30dca0d/sdk/go/google/container/v1/pulumiTypes.go#L7408

I believe you should be able to pass that as part of [monitoring config](https://github.com/pulumi/pulumi-google-native/blob/b588371cbcffbffb9dce59e5848353c7f30dca0d/sdk/go/google/container/v1/pulumiTypes.go#L8507) for the [cluster](https://github.com/pulumi/pulumi-google-native/blob/master/sdk/go/google/container/v1beta1/cluster.go#L417)
