### ISSUE TITLE
Changing Storage Bucket location does not replace it

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-google-native#490]
### What happened?

When updating the `location` property of a bucket, nothing happens.

### Steps to reproduce

1. Create a storage bucket.
2. Change it's location.

### Expected Behavior

I expect the bucket to be recreated.

### Actual Behavior

Nothing happens.

### Versions used

```
CLI
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @KaoruDev - thank you for this issue! We'll take a look as soon as we can.

**Comment by guineveresaenger** [comment]
Pulumi about:

```
@guin:google-native-490🦉 pulumi about
CLI          
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME           VERSION
google-native  0.19.1
nodejs         unknown

Host     
OS       darwin
Version  11.6
Arch     x86_64

This project is written in nodejs (/Users/guin/.nvm/versions/node/v14.18.1/bin/node v14.18.1)

Current Stack: dev

TYPE                             URN
pulumi:pulumi:Stack              urn:pulumi:dev::google-native-490::pulumi:pulumi:Stack::google-native-490-dev
pulumi:providers:google-native   urn:pulumi:dev::google-native-490::pulumi:providers:google-native::default_0_19_1
google-native:storage/v1:Bucket  urn:pulumi:dev::google-native-490::google-native:storage/v1:Bucket::guins-bucket


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/guinevere
User           guinevere
Organizations  guinevere, pulumi

NAME                   VERSION
@pulumi/google-native  0.19.1
@pulumi/pulumi         3.33.1
@types/node            14.18.18
```

**Comment by guineveresaenger** [comment]
And the dashboard activity shows that no updates reached google cloud:
<img width="809" alt="Screen Shot 2022-05-26 at 2 07 45 PM" src="https://user-images.githubusercontent.com/13116240/170580500-23276980-9395-4d64-90a1-3e395443f7ec.png">

**Comment by guineveresaenger** [comment]
Update: We're rolling out https://github.com/pulumi/pulumi-google-native/pull/453, which will pave the way to implement this resource properly. Stay tuned!

**Comment by viveklak** [comment]
While with #453 we now mark any changes to path elements to require replacement, buckets seem to be one of few resources which don't use location etc. in their path. I added overrides for this resource's metadata in #516.
