### ISSUE TITLE
Cannot update Service Account DisplayName 

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-google-native#514]
### What happened?

Similar to https://github.com/pulumi/pulumi-google-native/issues/300

When updating a `ServiceAccount.displayName` the following error gets thrown:

```
google-native:iam/v1:ServiceAccount (my-stack):
    error: error sending request: googleapi: Error 400: Invalid field mask for ServiceAccount. Field mask paths cannot be empty.: "https://iam.googleapis.com/v1/projects/my-project/serviceAccounts/my-svc-account@my-project.iam.gserviceaccount.com" map[serviceAccount:map[displayName:Updated name]]
```

### Steps to reproduce

1. Create a service account
2. Update its display name

### Expected Behavior

Display name of service account is updated.the 

### Actual Behavior

Error gets thrown.

### Versions used

```
CLI
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs (/home/kaoru/.asdf/shims/node v16.14.2)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
The change in #386 was a bit conservative when setting update mask - only doing so for resources that marked the field as required in the description. I believe this can be relaxed - see #515. I will validate that this is safe in that PR.

**Comment by viveklak** [comment]
Turns out #515 was not entirely safe since it messes with handling for resources with optional field-masks. Instead overriding and marking the fieldmask of `iam/v1:ServiceAccount` as required (which it implicitly is) in #518
