### ISSUE TITLE
TS type for EventArc trigger is wrong

### ISSUE THREAD

**Issue by ProfXponent** [pulumi/pulumi-google-native#571]
https://github.com/pulumi/pulumi-google-native/blob/257d4084c999223d735e8ca7d1251b7845bba586/sdk/nodejs/eventarc/v1/trigger.ts#L95

[The validateOnly prop should be boolean according to official docs](https://cloud.google.com/eventarc/docs/reference/rest/v1/projects.locations.triggers/create)

This causes an error on deploy and cannot be destroyed without manually editing state

**Comment by viveklak** [comment]
@ProfXponent thanks for filing the issue and apologies for the slow response. Looks like the provider generation process was assuming the query param types to be string only but there are boolean types supported as well. A fix is in #616
