### ISSUE TITLE
DNSSec on Domains Doesn't Work

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi-google-native#659]
### What happened?

Tried to enable DNSSec on a Cloud DNS domain

### Steps to reproduce

```
  const zone = new google.dns.v1.ManagedZone(domain.name, {
    dnsName: `${domain.domain}.`,
    dnssecConfig: {
      state: ManagedZoneDnsSecConfigState.Transfer,
    },
    description: "Managed DNS by Pulumi",
  });
```

### Expected Behavior

DNSSec of "Transfer" is visible on the Google Cloud Dashboard, but Pulumi has exited with a failure.

### Actual Behavior

```shell
  google-native:dns/v1:ManagedZone (example):
    error: waiting for completion: polling operation status: googleapi: Error 400: Invalid resource field value in the request.
    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "domain": "googleapis.com",
        "metadata": {
          "method": "cloud.dns.api.v1.ManagedZoneOperationsService.List",
          "service": "dns.googleapis.com"
        },
        "reason": "RESOURCE_PROJECT_INVALID"
      }
    ]
    , invalidParameter
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Hmm I just tried this and it seemed to work fine:
```
const zone = new google.dns.v1.ManagedZone("domain", {
    dnsName: `XXX.`,
    dnssecConfig: {
      state: "transfer",
    },
    description: "Managed DNS by Pulumi",
  });
```
<img width="1044" alt="Screen Shot 2022-08-29 at 10 47 11 AM" src="https://user-images.githubusercontent.com/1094518/187241611-25cf8bb0-1b96-4a4e-9163-bb049cc34c10.png">

**Comment by rawkode** [comment]
Fun, Googling for `cloud dns "RESOURCE_PROJECT_INVALID"` yields one result; this issue.

@viveklak Start with:

```
dnssecConfig: { state: "off" }
```

then after a `pulumi up`, change to `transfer`, and run `pulumi up` again.

**Comment by rawkode** [comment]
@viveklak @mikhailshilkov I did some more testing, ANY update to the `dns.v1.ManagedZone` resource causes this error - making this resource really painful to work with and rendering a stack it's part of rather brittle.

How can I help you get to the bottom of this?
