### ISSUE TITLE
Breaking change policy for discovery document

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#70]
What is the policy for breaking changes in discovery documents?

We observed [one example](https://github.com/pulumi/pulumi-google-native/pull/63/commits/d3700cd7c64a651ba593147ba587e1522c11f780#diff-8b66065880ad36c111fe7a8478316df33b8fb763056084edfad60c57898bd49fL997) so far - in `v1beta` version. Are these limited to pre-release versions? We installed the machinery to detect new breaking changes as they appear, so we'll extend this issue as we go.

We should find an official source.

**Comment by tequilarista** [comment]
Anything that is alpha or beta is not guaranteed.  Investigating if we have an official uniform policy that crosses all products but I suspect there may be variants

**Comment by mikhailshilkov** [comment]
@tequilarista This commit update discovery documents taking the changes of last two months: https://github.com/pulumi/pulumi-google-native/pull/131/commits/f75eb24305417d6aa39dc7abb43259860badd804#

There's a bunch of breaking changes there, including stable versions, e.g.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1454008/123067583-66d99480-d411-11eb-8c50-4cd615b75c46.png">

or

<img width="917" alt="image" src="https://user-images.githubusercontent.com/1454008/123067802-97b9c980-d411-11eb-8113-c63d399d893a.png">

You can see the printout here: https://github.com/pulumi/pulumi-google-native/pull/131#issuecomment-866565630

**Comment by mikhailshilkov** [comment]
You can see a few more examples of breaking changes listed in this comment: https://github.com/pulumi/pulumi-google-native/pull/151#issuecomment-877060373

**Comment by tequilarista** [comment]
I have confirmed there's no official public policy around this, however as part of our overall process we do diffs of discovery files as a way of updating CHANGLOGs that could be a useful pattern to emulate: [downloads.ts](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/generator/download.ts)
