### ISSUE TITLE
[internal] Investigate failing nightly-sdk-generation CI job

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-google-native#724]
https://github.com/pulumi/pulumi-google-native/actions/runs/3270749500/jobs/5379735477

It looks like the code generation is panicking, which is blocking automated updates to the provider SDKs.

**Comment by lblackstone** [comment]
@viveklak Do you recall the need for this check?
 https://github.com/pulumi/pulumi-google-native/blob/v0.26.1/provider/pkg/gen/discovery.go#L210-L213

This is resulting in the following error:
```
panic: get method "POST" is not supported: Document (discovery/contentwarehouse_v1.json)
```

**Comment by viveklak** [comment]
> @viveklak Do you recall the need for this check? https://github.com/pulumi/pulumi-google-native/blob/v0.26.1/provider/pkg/gen/discovery.go#L210-L213
> 
> This is resulting in the following error:
> 
> ```
> panic: get method "POST" is not supported: Document (discovery/contentwarehouse_v1.json)
> ```

Not sure - I think this has been around in some form since the initial stages of the provider. I imagine we should be ok since we use the http method etc. in the endpoint calculation but I can't guarantee we don't have an assumption for the get endpoint to be a "GET" elsewhere.
