### ISSUE TITLE
Trying to replace SslCertificate 

### ISSUE THREAD

**Issue by praveenperera** [pulumi/pulumi-google-native#729]
### What happened?

Running `pulumi up` few weeks/months after creating a SslCertificate (`new gcpn.compute.v1.SslCertificate`), pulumi attempts to replace it. Assuming because the cert renewed.  

### Work around

`ignoreChanges: ["managed.domainStatus", "managed.status", "certificate"]`

### Pulumi about

CLI          
Version      3.44.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME           VERSION
gcp            6.41.0
gcp            6.32.0
google-native  0.27.0
kubernetes     3.22.0
nodejs         unknown
random         4.8.2

Host     
OS       darwin
Version  12.6
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by praveenperera** [comment]
@roothorp I can confirm only `certificate` field needs to be ignored. So maybe this should just be a note in the docs, then?

**Comment by roothorp** [comment]
That's great to hear, thanks for the prompt feedback. I'll add a note to the docs now. Thanks!

**Comment by praveenperera** [comment]
Great I'll close the issue. Thanks
