### ISSUE TITLE
Set Pulumi user agent

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#73]
Set the user agent [here](https://github.com/pulumi/pulumi-google-native/blob/968254dfefa3fc1d2f5268a66e2ebcac8dbb79d8/provider/pkg/provider/http.go#L51) similar to [azure-native](https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/provider/provider.go#L1660). Do we have a partner ID to use?

- [ ] Follow the example format below.
- [ ] A user should be able to opt-out or modify the user agent.

Suggested format:

`<prod_name>/ver (GPN:<company name>; <other comments>) <other prod>/ver`

Example:

`Product_A/1.1 (GPN:Partner_ABC; staging) Product_B/1.3 Google­HTTP­Java­Client/1.20.0`

*User Agent compliance with RFC (http://tools.ietf.org/html/rfc7231#section­5.5.3)

**Comment by isaac-pulumi** [comment]
I've asked our partner for feedback here.

**Comment by isaac-pulumi** [comment]
Suggested format
"<prod_name>/ver (GPN:<company name>; <other comments>) <other prod>/ver "​*
Example
"Product_A/1.1 (GPN:Partner_ABC; staging) Product_B/1.3 Google­HTTP­Java­Client/1.20.0"
*User Agent compliance with RFC (http://tools.ietf.org/html/rfc7231#section­5.5.3)

**Comment by infin8x** [comment]
Can/should we also do this in the non-native provider?

**Comment by mikhailshilkov** [comment]
> Can/should we also do this in the non-native provider?

I think we can, we did this in Azure-Classic
