### ISSUE TITLE
[internal] Nightly update job blocked on codegen bug

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-google-native#735]
https://github.com/pulumi/pulumi/issues/11251 is currently breaking the generated Go SDK using the latest discovery docs.

**Comment by mikhailshilkov** [comment]
https://github.com/pulumi/pulumi/issues/11251 is now resolved

**Comment by lblackstone** [comment]
Working on a fix in https://github.com/pulumi/pulumi-google-native/pull/733
