### ISSUE TITLE
Upgrading from 0.20.0 to 0.21.0 in Typescript changes auto-name results

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-google-native#809]
### What happened?

Upgrading from `0.20.0` to `0.21.0` triggered a name update to `storage.v1.Bucket` and `compute.v1.SslPolicy` because the auto-name result is different.

### Steps to reproduce

1. Using the `0.20.0` typescript module create a `storage.v1.Bucket`
2. Upgrade to `0.21.0`.
3. Notice the Pulumi preview is proposing a replacement of the bucket because the auto-name result changed.

### Expected Behavior

No changes made to physical resources.

### Actual Behavior

Pulumi wants to replace the physical resource because the name is different.

### Output of `pulumi about`

```
CLI
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Host
OS       darwin
Version  12.6.2
Arch     x86_64
```

### Additional context

I avoided replacement by adding `ignoreChanges: ["name"]` to the resources. However, this doesn't seem like a long-term solution.

The issue is also present in `0.27.0`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by KaoruDev** [comment]
Okay now I can't reproduce it -- le sigh -- however my live stacks are still impacted. Will see what `ignoreChanges: ["name"]` -- maybe we'll just live with it.

**Comment by KaoruDev** [comment]
Oh ok found out why I couldn't reproduce it, the changes I was testing were using the `ignoreChanges: ["name"]` -- doh!

So the steps in the original ticket should still work.

This also is impacting:
* `google-native:compute/v1:Firewall`
* `google-native:compute/v1:Router`

Trying to update them results in this error:

Firewall:
```
error: error sending request: googleapi: Error 400: Invalid value for field 'resource': '{  "name": "firewall-509a4d7",  "description": "fire!",  "network": "https://...'. he resource name in the request needs to match the existing resource name., invalid: "https://www.googleapis.com/compute/v1/projects/my-project/global/firewalls/firewall-a6b9f31" map[allowed:[map[IPProtocol:tcp ports:[22]]] description:fire!:firewall-509a4d7 network:https://www.googleapis.com/compute/v1/projects/my-project/global/networks/main sourceRanges:[1.0.0.0/20] targetTags:[firewall]]
```

Router:
```
   error: error sending request: googleapi: Error 400: Invalid value for field 'resource': '{  "name": "router-894db0b",  "network": "https://www.googleapis.com/compute/v1/projects/my-project...'. The resource name in the request needs to match the existing resource name., invalid: "https://www.googleapis.com/compute/v1/projects/my-project/regions/us-east1/routers/router-392c826" map[name:router-894db0b nats:[map[enableDynamicPortAllocation:true name:compute-subnets-us-east1 natIpAllocateOption:AUTO_ONLY sourceSubnetworkIpRangesToNat:LIST_OF_SUBNETWORKS subnetworks:[map[name:https://www.googleapis.com/compute/v1/projects/my-project/regions/us-east1/subnetworks/vm-subnet-151f8e9 sourceIpRangesToNat:[ALL_IP_RANGES]]]]] network:https://www.googleapis.com/compute/v1/projects/my-project/global/networks/main]
   ```

**Comment by KaoruDev** [comment]
Ok -- seems like running `pulumi refresh` resolves the issue. No idea why. https://github.com/pulumi/pulumi/issues/2247 would've helped here!

**Comment by KaoruDev** [comment]
So unfortunately running `pulumi refresh` worked on newer stacks but not older stacks -- I ended up adding `ignoreChanges: ["name"]` to impacted resources, but would love a different work around.

**Comment by KaoruDev** [comment]
Ok -- there are actually too many resources this is impacting so I decided not to upgrade for now. Gonna reopen in case others are experiencing this.

**Comment by KaoruDev** [comment]
Hey @squaremo -- I, unfortunately, have critical resources managed by this provider so I cannot incur the downtime (i.e. I have a few buckets that I cannot lose data on). I suspect I may be able to get around this by switching to the classic provider and using `import` function.

I understand this provider is in `preview` -- I just wanted to raise this issue so that it doesn't occur when it's not in `preview`. We may permanently switch over to the classic provider if we can't find a way to upgrade the native library. Hopefully, the issues I've reported thus far helped the team.

**Comment by squaremo** [comment]
@KaoruDev Got it -- thanks for being understanding. I think switching to 'classic for your critical resources is sensible for the time being.

> Hopefully, the issues I've reported thus far helped the team.

Absolutely, thank you for persevering!
