### ISSUE TITLE
Unique method names

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#83]
The majority of methods in discovery documents use standard names for CRUD operations: "create", "get", "update", and "delete". However, there are some snowflakes:

- [`dropDatabase`](https://github.com/pulumi/pulumi-google-native/blob/968254dfefa3fc1d2f5268a66e2ebcac8dbb79d8/discovery/spanner_v1.json#L963) in Spanner
- [`replaceService`](https://github.com/pulumi/pulumi-google-native/blob/968254dfefa3fc1d2f5268a66e2ebcac8dbb79d8/discovery/run_v1.json#L799) in Cloud Run
- [`insert`](https://github.com/pulumi/pulumi-google-native/blob/968254dfefa3fc1d2f5268a66e2ebcac8dbb79d8/discovery/storage_v1.json#L481) in Storage

Are those name differences significant? How do we discover all of them?

**Comment by tequilarista** [comment]
Unfortunately there will be these types of scenarios some of which may be very specific to the product/feature they're exposing.  If you have specific areas of confusion we can try and get further information but there's not going to be 100% uniformity across all products unfortunately.
