### ISSUE TITLE
Missing API for container registries?

### ISSUE THREAD

**Issue by djc** [pulumi/pulumi-google-native#834]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I was using `import Registry} from '@pulumi/gcp/container'` in the classic GCP API, but I haven't been able to find a replacement in the google-native API. I know we should probably start using `ArtifactRegistry` instead, but IMO it would still be nice if the migration from gcp to google-native didn't require that to be done at the same time.

(Or am I just missing this API? I did look for it in the documentation reference and also searched this repository.)

**Comment by lukehoban** [comment]
I believe the `gcp.container.Registry` API isn't a real physical resource in Google Cloud, and is just an API to ensure that a certainly named bucket exists in GCS.  That is per the docs at https://www.pulumi.com/registry/packages/gcp/api-docs/container/registry/.

We could plausibly add a similar concept to google-native, but it appears this is outside of the formal API specification of Google Cloud.  Specifically - there are no APIs related to Registry defined in the Discovery Docs for the `container/v1` namespace - which is what is used to define the Google Native provider.

My understanding from the GCR documentation is that just hitting the gcr.io API (via a docker pull or docker push for example) will automatically create this bucket if it doesn't exist transparently.  So I'm not sure it should be strictly necessary to have a Pulumi-level resource to manage this.

If there is a specific scenario you are trying to accomplish which you can't - could you share a code snippet of what isn't working?

**Comment by djc** [comment]
Thanks for the explanation, makes sense! I was just trying to port some gcp code to google-native code, so I'll find some other way to do this (either by creating the GCS bucket explicitly or by migrating to Artifact Registry before migrating my Pulumi code).
