### ISSUE TITLE
Google Analytics + Tag Manager

### ISSUE THREAD

**Issue by max-ostapenko** [pulumi/pulumi-google-native#839]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I'd like to use Pulumi to manage configuration of [Google Analytics](https://developers.google.com/analytics/devguides/config/admin/v1/rest) and [Tag Manager](https://developers.google.com/tag-platform/tag-manager/api/v2) accounts.
It would improve analytics operations, workflows and governance, e.g.:
1. use structured configuration documentation as configuration input,
2. deploy the configuration to the test accounts for testing,
3. after QA rollout the updated configuration to the multiple prod accounts.

Use cases:
- Having such workflow could help companies manage analytics migrations ([e.g. from UA to GA4](https://support.google.com/analytics/answer/10759417)).
- There is a big variety of tools that assist with managing small parts of configuration, both private and public. ([example](https://www.simoahava.com/tools/google-analytics-custom-dimension-manager/)).

P.S. Do I understand correctly that the Google Cloud is *not* the only application for this package, and other Google services can be expected to be included too?

**Comment by rquitales** [comment]
Hi @max-ostapenko thanks for filing this request.

The Google native provider is only meant to interact with Google Cloud Platform services and we do not intend on expanding its surface area to target other Google services at this stage in time.
