### ISSUE TITLE
Don't include API version to type names

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#869]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`apikeys.v2.Key` resource has argument types that are all named with a `V2` prefix in type names, e.g. [`V2AndroidApplicationArgs`](https://github.com/pulumi/pulumi-google-native/blob/master/sdk/python/pulumi_google_native/apikeys/v2/_inputs.py#L23) or `V2Restrictions`. Those names come from the [discovery docs](https://github.com/pulumi/pulumi-google-native/blob/5d845649e49dc057953c5fd48e3d49fee9a4ba56/discovery/apikeys_v2.json#L643).

Why not call them just "Restrictions"? Two downsides of the current naming that I see:
1. User's code is polluted with these less readable strings.
2. If V3 comes out and users want to migrate, they will have to rename all the types they used in their code.

**Comment by pinalbaldha** [comment]
For apikeys API, above naming pattern(${version}${name}) is unintended. It is a mistake. 
For new methods and upcoming versions, names will be corrected.
For existing apis, names can't be corrected due to backward compatibility.
