### ISSUE TITLE
Incorrect args for project creation

### ISSUE THREAD

**Issue by Ezard** [pulumi/pulumi-google-native#89]
`ProjectArgs` imported from `@pulumi/gcp-native/cloudresourcemanager/v3` has both `projectId` and `projectsId` as fields, with the former being optional and the latter being required

However, according to the [discovery document](https://cloudresourcemanager.googleapis.com/$discovery/rest?version=v3) and also the [API docs](https://cloud.google.com/resource-manager/reference/rest/v3/projects#Project), `projectsId` should not exist and `projectId` should be required

**Comment by mikhailshilkov** [comment]
The `projectsId` property is part of the URL path `v3/projects/{projectsId}`. We will likely rename it to `projectId` and merge with the body property in the future.

> projectId should be required

Could you point me to where it's marked as required? I only see this:

```json
"projectId": {
    "description": "Immutable. The unique, user-assigned id of the project. It must be 6 to 30 lowercase ASCII letters, digits, or hyphens. It must start with a letter. Trailing hyphens are prohibited. Example: `tokyo-rain-123`",
    "type": "string"
},
```

**Comment by Ezard** [comment]
@mikhailshilkov I was working off the basis that some fields are marked as "optional" in the docs (e.g. `parent` and `displayName`), whereas `projectId` is not

Also, based on the [gcloud CLI docs for creating projects](https://cloud.google.com/sdk/gcloud/reference/projects/create), a project ID is the only required data. When using the CLI, if you specify just a name and not a project ID then the CLI will auto-suggest a project ID for you; I'm unsure if this is also the case for the REST API

I'm not massively familiar with the discovery document format though, so I'm unsure how "required" parameters are specified
