### ISSUE TITLE
Typescript definitions for enum types should use string unions or enums

### ISSUE THREAD

**Issue by Ezard** [pulumi/pulumi-google-native#90]
For cases where the Google Cloud discovery document provides an enum of possible values for a string field or parameter, the types generated by Pulumi should generate a string union/enum of these values and use that, instead of just a plain string. This would allow values to be autocompleted by IDEs (and therefore saving users from having to check allowed values in GCP's web docs), and would prevent invalid values from ever even reaching Pulumi since they'd be caught by the Typescript compiler first.

**Comment by mikhailshilkov** [comment]
Indeed. Also, this applies to all languages, not just TypeScript. Let's track enums here: https://github.com/pulumi/pulumi-google-native/issues/86
