### ISSUE TITLE
Pulumi Fails to Create a BigQuery View Table that References a Table from Another Project

### ISSUE THREAD

**Issue by cwhitemaddox** [pulumi/pulumi-google-native#959]
### What happened?

When attempting to create a BigQuery View Table, `pulumi up` failed to create the View resource with the error:

```
  gcp:bigquery:Table (temp_view):
    error: 1 error occurred:
        * googleapi: Error 404: Not found: Dataset [redacted], notFound
```

The View it failed to create references a table from a different project in the `FROM` clause of the View's query statement (see example below).

### Example

```ts
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

// Replace these variable values with your project's information
const currentProject = "some-gcp-project"; // The project where the view will reside
const externalProject = "another-gcp-project"; // The project where the existing dataset and table are located
const datasetId = "temp_dataset"; // The ID of the dataset where the view will be created
const viewId = "temp_view"; // The ID for the view
const externalDatasetId = "existing_dataset"; // The ID of the already existing external dataset
const externalTableId = "existing_table"; // The ID of the already existing external table

// Create a BigQuery Dataset
const dataset = new gcp.bigquery.Dataset(datasetId, {
  datasetId: datasetId,
  description: "This is a test description",
  friendlyName: "Temp Dataset",
  location: "us-central1",
  project: currentProject,
});

// Create a BigQuery View
const view = new gcp.bigquery.Table(viewId, {
  datasetId: dataset.datasetId,
  tableId: viewId,
  project: currentProject,
  view: {
    // Here the query references a table from another BigQuery dataset in a different project
    query: `SELECT * FROM \`${externalProject}.${externalDatasetId}.${externalTableId}\``,
    useLegacySql: false, // Ensure to use standard SQL
  },
});

// Export the ID and selfLink of the new BigQuery view
export const viewSelfLink = view.selfLink;
export const viewIdOutput = view.id;
```

This example is from [this thread with Pulumi AI](https://www.pulumi.com/ai/conversations/593f3948-8a2b-420b-8ca4-cd8739980aed) (and fundamentally the same as what I initially tried when I first got the error).

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.102.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/cwhite/.nvm/versions/node/v16.20.2/bin/node' version='v16.20.2'
```

### Additional context

I have confirmed that the user `pulumi up` is running as has permissions to view, etc. the `existing_dataset` and `existing_table` that are already in the `another-gcp-project` GCP project. Listing them with the `bq` CLI, for instance, works fine.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for filing this issue @cwhitemaddox; I would suggest trying the program with [Verbose debugging](https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging) enabled to see the raw API call the provider is making and debug the error from the API more directly. 

Alternatively, you can try falling back to the [GCP provider](https://www.pulumi.com/registry/packages/gcp/) for this resource.

**Comment by cwhitemaddox** [comment]
@mjeffryes Just realized that (I'm fairly certain) I'm using the GCP provider (`import * as gcp from "@pulumi/gcp";`) and not the `google-native-provider` , so I mistakenly opened this issue in the wrong repo (here)...

I did rerun the command with verbose logging, but I didn't get much more info about the error (despite the logging being helpfully more verbose). We're going to use Terraform for the time being, so I haven't dug further. I appreciate your help :pray:
