### ISSUE TITLE
Regional GKE clusters not possible since zone - a deprecated field - is required by the ClusterArgs class

### ISSUE THREAD

**Issue by brandonjbjelland** [pulumi/pulumi-google-native#99]
Working within the Python SDK and trying some basic provisioning tasks against the container API. The specific issue I hit here is as the title describes: a class-required attribute, `zone`, means creation of any GKE clusters is necessarily zonal instead of regional which also means the autopilot cluster mode is currently impossible.

Proposed general solution: Looking at the [REST API doc](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/create), `zone` (amongst others) is a deprecated field. In cases where we can reliably know an attribute is deprecated, the code generator should omit the field from the schema entirely.

## Expected behavior

I would expect to be able to omit the `zone` attribute and instead use `location` to specify the region to create a regional cluster.

## Current behavior

Currently, only zonal GKE clusters can be created via the Python (and I assume other), SDKs.

## Steps to reproduce

1. Try to instantiate `pulumi_google_native.container.v1beta1.ClusterArgs()` without specifying a `zone`. This will fail.
2. Give a zone.
3. With the other attributes satisfied, you now have a zonal cluster. Regional clusters are not possible to create if the `zone` attribute is given.

## Context (Environment)

I'm simply trying to create either a:
1. autopilot cluster - necessarily regional or
2. a regional standard GKE cluster

## Affected feature

The problem I hit is specific to GKE clusters but there's very much a generalized story here around deprecated fields. I haven't dug into if there's a dedicated field within a discovery API element that denotes deprecation status of a field but even in absence of this, the description of `zone` reads:

```python
        :param pulumi.Input[str] zone: [Output only] The name of the Google Compute Engine [zone](https://cloud.google.com/compute/docs/zones#available) in which the cluster resides. This field is deprecated, use location instead.
```

I think any fields that have some pattern that matches "This field is deprecated" or other known patterns of deprecated should likely be omitted from what the code generator pushes to the libraries.

**Comment by mikhailshilkov** [comment]
Hi @brandonjbjelland thank you for reporting this.

I'm not claiming our behavior for `v1beta1` is correct - but I'm curious why you are using `v1beta1` instead of `v1`. I think this problem doesn't apply to our `v1` resource as shown in [this example](https://github.com/pulumi/examples/blob/master/google-native-ts-k8s-ruby-on-rails-postgresql/infra/cluster.ts#L10)

**Comment by brandonjbjelland** [comment]
Thanks for the reply and gold suggestion.

To my knowledge, the autopilot field is only available on the beta API, so I started there.

**Comment by mikhailshilkov** [comment]
We appreciate your comment, you are 100% correct. I have a PR open that will fix this issue in the next version.
